"""Add EVM module

Revision ID: 149e4a80496f
Revises: 631933e956af
Create Date: 2026-09-12 15:35:09.138996
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '149e4a80496f'
down_revision: Union[str, Sequence[str], None] = '631933e956af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evm_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('baseline_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'baseline_number', name='uq_evm_baselines_project_number')
    )
    op.create_index(op.f('ix_evm_baselines_project_id'), 'evm_baselines', ['project_id'], unique=False)
    op.create_index(op.f('ix_evm_baselines_status'), 'evm_baselines', ['status'], unique=False)
    op.create_index('ix_evm_baselines_single_approved', 'evm_baselines', ['project_id'], unique=True, postgresql_where=sa.text("status = 'Approved'"))
    op.create_table('evm_baseline_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('baseline_id', sa.UUID(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('planned_percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('planned_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('planned_percentage >= 0 AND planned_percentage <= 100', name='ck_evm_baseline_periods_percentage'),
    sa.CheckConstraint('planned_value >= 0', name='ck_evm_baseline_periods_value_nonnegative'),
    sa.ForeignKeyConstraint(['baseline_id'], ['evm_baselines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baseline_id', 'period_date', name='uq_evm_baseline_periods_baseline_date')
    )
    op.create_index(op.f('ix_evm_baseline_periods_baseline_id'), 'evm_baseline_periods', ['baseline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evm_baseline_periods_baseline_id'), table_name='evm_baseline_periods')
    op.drop_table('evm_baseline_periods')
    op.drop_index('ix_evm_baselines_single_approved', table_name='evm_baselines')
    op.drop_index(op.f('ix_evm_baselines_status'), table_name='evm_baselines')
    op.drop_index(op.f('ix_evm_baselines_project_id'), table_name='evm_baselines')
    op.drop_table('evm_baselines')
    # ### end Alembic commands ###
