"""add_ra_billing

Revision ID: 631933e956af
Revises: d9a8b7c6e5f4
Create Date: 2026-09-12 13:44:52.602700
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '631933e956af'
down_revision: Union[str, Sequence[str], None] = 'd9a8b7c6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ra_bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('deductions_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('net_payable', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('deductions_amount >= 0', name='ck_ra_bills_deductions_nonnegative'),
    sa.CheckConstraint('gross_amount >= 0', name='ck_ra_bills_gross_nonnegative'),
    sa.CheckConstraint('net_payable >= 0', name='ck_ra_bills_net_nonnegative'),
    sa.CheckConstraint('period_from <= period_to', name='ck_ra_bills_period'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'bill_number', name='uq_ra_bills_contract_bill_number')
    )
    op.create_index(op.f('ix_ra_bills_contract_id'), 'ra_bills', ['contract_id'], unique=False)
    op.create_index(op.f('ix_ra_bills_status'), 'ra_bills', ['status'], unique=False)
    op.create_table('ra_bill_deductions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ra_bill_id', sa.UUID(), nullable=False),
    sa.Column('deduction_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_ra_bill_deductions_amt_nonnegative'),
    sa.ForeignKeyConstraint(['ra_bill_id'], ['ra_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ra_bill_deductions_ra_bill_id'), 'ra_bill_deductions', ['ra_bill_id'], unique=False)
    op.create_table('ra_bill_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ra_bill_id', sa.UUID(), nullable=False),
    sa.Column('boq_item_id', sa.UUID(), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.CheckConstraint('current_amount >= 0', name='ck_ra_bill_items_amt_nonnegative'),
    sa.CheckConstraint('current_quantity >= 0', name='ck_ra_bill_items_qty_nonnegative'),
    sa.CheckConstraint('rate >= 0', name='ck_ra_bill_items_rate_nonnegative'),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ),
    sa.ForeignKeyConstraint(['ra_bill_id'], ['ra_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ra_bill_id', 'boq_item_id', name='uq_ra_bill_items_bill_boq')
    )
    op.create_index(op.f('ix_ra_bill_items_boq_item_id'), 'ra_bill_items', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_ra_bill_items_ra_bill_id'), 'ra_bill_items', ['ra_bill_id'], unique=False)
    op.create_table('ra_bill_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ra_bill_item_id', sa.UUID(), nullable=False),
    sa.Column('measurement_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ),
    sa.ForeignKeyConstraint(['ra_bill_item_id'], ['ra_bill_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement_id')
    )
    op.create_index(op.f('ix_ra_bill_measurements_ra_bill_item_id'), 'ra_bill_measurements', ['ra_bill_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ra_bill_measurements_ra_bill_item_id'), table_name='ra_bill_measurements')
    op.drop_table('ra_bill_measurements')
    op.drop_index(op.f('ix_ra_bill_items_ra_bill_id'), table_name='ra_bill_items')
    op.drop_index(op.f('ix_ra_bill_items_boq_item_id'), table_name='ra_bill_items')
    op.drop_table('ra_bill_items')
    op.drop_index(op.f('ix_ra_bill_deductions_ra_bill_id'), table_name='ra_bill_deductions')
    op.drop_table('ra_bill_deductions')
    op.drop_index(op.f('ix_ra_bills_status'), table_name='ra_bills')
    op.drop_index(op.f('ix_ra_bills_contract_id'), table_name='ra_bills')
    op.drop_table('ra_bills')
    # ### end Alembic commands ###
